### ISSUE TITLE
Create Model for reviews

### ISSUE THREAD

**Issue by samdoghor** [samdoghor/GomerceBE#40]

**Comment by dopewevmond** [comment]
done and pushed to a [new branch](https://github.com/samdoghor/GomerceBE/tree/add-review-schema). i'm waiting for the _products_ and _sellers_ tables to be created so i can test this model and create a PR with the migration files intact.

**Comment by samdoghor** [comment]
Ok. Just Relax. Push first we want to review first, after which you would amend as required and give final push.

**Comment by samdoghor** [comment]
Reopened
