### ISSUE TITLE
Create Schema for Payment details

### ISSUE THREAD

**Issue by samdoghor** [samdoghor/GomerceBE#8]

**Comment by dopewevmond** [comment]
Noted. I'll start working on it immediately.

Regards

**Comment by dopewevmond** [comment]
Hello, 

I'd like to know if there's an agreed upon convention for naming the database tables .ie. camelCase or snake_case. Also, some of the database table names are singular whilst some are plural. Lastly, _order_ is a keyword in sql so maybe we should not use it as a table name? I was not able to join the last meeting so pardon me if you've already addressed some of these issues

Regards

**Comment by samdoghor** [comment]
There was no agreed naming format for the tables however the camelCase is totally a good use. We are using singular words for the table names. We would review these on the diagram schema. We would see to the order table as regard your concern in our next meeting. Thank you.
