### ISSUE TITLE
Role Base Authorization for Super Admin, Admin and Vendors

### ISSUE THREAD

**Issue by samdoghor** [samdoghor/GomerceBE#84]
https://www.figma.com/file/IJugEUzUNYedee0g9Qex70/Gomerce?node-id=129%3A505&t=Xp6bg1tVl0Ud5AFu-0 

Use as Reference

**Comment by Bappa-Kamba** [comment]
Hello, you could go ahead and check the Auth0 account, I've finalized the roles.

**Comment by samdoghor** [comment]
Confirmed
