### ISSUE TITLE
Route for Admin to CRUD product categories

### ISSUE THREAD

**Issue by samdoghor** [samdoghor/GomerceBE#87]
https://www.figma.com/file/IJugEUzUNYedee0g9Qex70/Gomerce?node-id=129%3A505&t=Xp6bg1tVl0Ud5AFu-0

Use as Reference

**Comment by yuvenalmash** [comment]
Hello @samdoghor,
Can I get more details on this, so that I can get started

**Comment by samdoghor** [comment]
Please, WhatsApp. Sorry for the late response...
