### ISSUE TITLE
Route for Admin to View and Delete Reviews

### ISSUE THREAD

**Issue by samdoghor** [samdoghor/GomerceBE#89]
https://www.figma.com/file/IJugEUzUNYedee0g9Qex70/Gomerce?node-id=129%3A505&t=Xp6bg1tVl0Ud5AFu-0

Use as Reference

**Comment by dmdhassan** [comment]
Hi @TangoIndiaMango, can we sync ? What’s your name on the WhatsApp group

**Comment by TangoIndiaMango** [comment]
sorry for late reply. It's Timmy.
